; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Feb 18 2021 12:59:29 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAY6NUGB0H0S:
	dc.w $0, DATAY6NUGB0H0S_1-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_2-DATAY6NUGB0H0S, DATAY6NUGB0H0S_3-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_4-DATAY6NUGB0H0S, DATAY6NUGB0H0S_5-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_6-DATAY6NUGB0H0S, DATAY6NUGB0H0S_7-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_8-DATAY6NUGB0H0S, DATAY6NUGB0H0S_9-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_A-DATAY6NUGB0H0S, DATAY6NUGB0H0S_B-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_C-DATAY6NUGB0H0S, DATAY6NUGB0H0S_D-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_E-DATAY6NUGB0H0S, DATAY6NUGB0H0S_F-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_10-DATAY6NUGB0H0S, DATAY6NUGB0H0S_11-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_12-DATAY6NUGB0H0S, DATAY6NUGB0H0S_13-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_14-DATAY6NUGB0H0S, DATAY6NUGB0H0S_15-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_16-DATAY6NUGB0H0S, DATAY6NUGB0H0S_17-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_18-DATAY6NUGB0H0S, DATAY6NUGB0H0S_19-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_1A-DATAY6NUGB0H0S, DATAY6NUGB0H0S_1B-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_1C-DATAY6NUGB0H0S, DATAY6NUGB0H0S_1D-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_1E-DATAY6NUGB0H0S, DATAY6NUGB0H0S_1F-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_20-DATAY6NUGB0H0S, DATAY6NUGB0H0S_21-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_22-DATAY6NUGB0H0S, DATAY6NUGB0H0S_23-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_24-DATAY6NUGB0H0S, DATAY6NUGB0H0S_25-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_26-DATAY6NUGB0H0S, DATAY6NUGB0H0S_27-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_28-DATAY6NUGB0H0S, DATAY6NUGB0H0S_29-DATAY6NUGB0H0S
	dc.w $0, $0
	dc.w DATAY6NUGB0H0S_2C-DATAY6NUGB0H0S, DATAY6NUGB0H0S_2D-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_2E-DATAY6NUGB0H0S, DATAY6NUGB0H0S_2F-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_30-DATAY6NUGB0H0S, DATAY6NUGB0H0S_31-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_32-DATAY6NUGB0H0S, DATAY6NUGB0H0S_33-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_34-DATAY6NUGB0H0S, DATAY6NUGB0H0S_35-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_36-DATAY6NUGB0H0S, DATAY6NUGB0H0S_37-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_38-DATAY6NUGB0H0S, DATAY6NUGB0H0S_39-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_3A-DATAY6NUGB0H0S, DATAY6NUGB0H0S_3B-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_3C-DATAY6NUGB0H0S, DATAY6NUGB0H0S_3D-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_3E-DATAY6NUGB0H0S, DATAY6NUGB0H0S_3F-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_40-DATAY6NUGB0H0S, DATAY6NUGB0H0S_41-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_42-DATAY6NUGB0H0S, DATAY6NUGB0H0S_43-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_44-DATAY6NUGB0H0S, DATAY6NUGB0H0S_45-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_46-DATAY6NUGB0H0S, DATAY6NUGB0H0S_47-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_48-DATAY6NUGB0H0S, DATAY6NUGB0H0S_49-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_4A-DATAY6NUGB0H0S, DATAY6NUGB0H0S_4B-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_4C-DATAY6NUGB0H0S, DATAY6NUGB0H0S_4D-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_4E-DATAY6NUGB0H0S, DATAY6NUGB0H0S_4F-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_50-DATAY6NUGB0H0S, DATAY6NUGB0H0S_51-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_52-DATAY6NUGB0H0S, DATAY6NUGB0H0S_53-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_54-DATAY6NUGB0H0S, DATAY6NUGB0H0S_55-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_56-DATAY6NUGB0H0S, DATAY6NUGB0H0S_57-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_58-DATAY6NUGB0H0S, DATAY6NUGB0H0S_59-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_5A-DATAY6NUGB0H0S, DATAY6NUGB0H0S_5B-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_5C-DATAY6NUGB0H0S, DATAY6NUGB0H0S_5D-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_5E-DATAY6NUGB0H0S, DATAY6NUGB0H0S_5F-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_60-DATAY6NUGB0H0S, DATAY6NUGB0H0S_61-DATAY6NUGB0H0S
	dc.w DATAY6NUGB0H0S_62-DATAY6NUGB0H0S, DATAY6NUGB0H0S_63-DATAY6NUGB0H0S
DATAY6NUGB0H0S_1: dc.b $2
	dc.b $ED, $B, $0, $0, $F2
	dc.b $D, $C, $0, $C, $F2
DATAY6NUGB0H0S_2: dc.b $2
	dc.b $ED, $B, $0, $0, $F2
	dc.b $D, $C, $0, $C, $F2
DATAY6NUGB0H0S_3: dc.b $2
	dc.b $ED, $B, $0, $0, $F2
	dc.b $D, $C, $0, $C, $F2
DATAY6NUGB0H0S_4: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATAY6NUGB0H0S_5: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATAY6NUGB0H0S_6: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATAY6NUGB0H0S_7: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATAY6NUGB0H0S_8: dc.b $2
	dc.b $ED, $B, $0, $0, $F2
	dc.b $D, $C, $0, $C, $F2
DATAY6NUGB0H0S_9: dc.b $2
	dc.b $ED, $B, $0, $0, $F4
	dc.b $D, $8, $0, $C, $F4
DATAY6NUGB0H0S_A: dc.b $2
	dc.b $EE, $A, $0, $0, $EF
	dc.b $6, $9, $0, $9, $F7
DATAY6NUGB0H0S_B: dc.b $2
	dc.b $EC, $A, $0, $0, $EE
	dc.b $4, $9, $0, $9, $F6
DATAY6NUGB0H0S_C: dc.b $3
	dc.b $C, $C, $0, $0, $EB
	dc.b $EC, $B, $0, $4, $F3
	dc.b $FC, $2, $0, $10, $B
DATAY6NUGB0H0S_D: dc.b $4
	dc.b $5, $5, $0, $0, $EB
	dc.b $ED, $A, $0, $4, $F3
	dc.b $5, $4, $0, $D, $FB
	dc.b $D, $4, $0, $F, $3
DATAY6NUGB0H0S_E: dc.b $2
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $8, $0, $C, $F3
DATAY6NUGB0H0S_F: dc.b $4
	dc.b $FC, $C, $0, $0, $EC
	dc.b $EC, $9, $0, $4, $F4
	dc.b $4, $9, $0, $A, $F4
	dc.b $FC, $1, $0, $10, $C
DATAY6NUGB0H0S_10: dc.b $3
	dc.b $F4, $F, $0, $0, $F0
	dc.b $EC, $8, $0, $10, $F8
	dc.b $FC, $0, $0, $13, $10
DATAY6NUGB0H0S_11: dc.b $4
	dc.b $5, $5, $0, $0, $ED
	dc.b $ED, $A, $0, $4, $F5
	dc.b $5, $8, $0, $D, $FD
	dc.b $D, $4, $0, $10, $5
DATAY6NUGB0H0S_12: dc.b $2
	dc.b $EE, $B, $0, $0, $F4
	dc.b $E, $4, $0, $C, $F4
DATAY6NUGB0H0S_13: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAY6NUGB0H0S_14: dc.b $5
	dc.b $F2, $D, $0, $0, $EB
	dc.b $EA, $4, $0, $8, $F3
	dc.b $2, $C, $0, $A, $F3
	dc.b $A, $5, $0, $E, $FB
	dc.b $FA, $4, $0, $12, $B
DATAY6NUGB0H0S_15: dc.b $5
	dc.b $EE, $9, $0, $0, $EB
	dc.b $F6, $2, $0, $6, $3
	dc.b $FE, $4, $0, $9, $F3
	dc.b $FE, $5, $0, $B, $B
	dc.b $6, $1, $0, $F, $FB
DATAY6NUGB0H0S_16: dc.b $4
	dc.b $F5, $C, $0, $0, $EC
	dc.b $ED, $4, $0, $4, $F4
	dc.b $FD, $C, $0, $6, $F4
	dc.b $5, $9, $0, $A, $FC
DATAY6NUGB0H0S_17: dc.b $6
	dc.b $EC, $A, $0, $0, $ED
	dc.b $4, $C, $0, $9, $F5
	dc.b $C, $4, $0, $D, $FD
	dc.b $F4, $1, $0, $F, $5
	dc.b $14, $0, $0, $11, $5
	dc.b $FC, $0, $0, $12, $D
DATAY6NUGB0H0S_18: dc.b $5
	dc.b $EB, $A, $0, $0, $EC
	dc.b $3, $9, $0, $9, $F4
	dc.b $13, $4, $0, $F, $FC
	dc.b $F3, $5, $0, $11, $4
	dc.b $3, $0, $0, $15, $C
DATAY6NUGB0H0S_19: dc.b $5
	dc.b $EE, $A, $0, $0, $EE
	dc.b $E6, $0, $0, $9, $F6
	dc.b $6, $5, $0, $A, $F6
	dc.b $F6, $9, $0, $E, $6
	dc.b $6, $0, $0, $14, $6
DATAY6NUGB0H0S_1A: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATAY6NUGB0H0S_1B: dc.b $6
	dc.b $F3, $C, $0, $0, $EB
	dc.b $EB, $4, $0, $4, $F3
	dc.b $FB, $C, $0, $6, $F3
	dc.b $3, $5, $0, $A, $FB
	dc.b $13, $0, $0, $E, $3
	dc.b $3, $0, $0, $F, $B
DATAY6NUGB0H0S_1C: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $ED, $8, $0, $C, $FC
	dc.b $F5, $3, $0, $F, $C
DATAY6NUGB0H0S_1D: dc.b $4
	dc.b $F5, $E, $0, $0, $ED
	dc.b $D, $4, $0, $C, $5
	dc.b $ED, $1, $0, $E, $D
	dc.b $5, $0, $0, $10, $D
DATAY6NUGB0H0S_1E: dc.b $2
	dc.b $F6, $E, $0, $0, $EE
	dc.b $F6, $2, $0, $C, $E
DATAY6NUGB0H0S_1F: dc.b $4
	dc.b $F4, $E, $0, $0, $ED
	dc.b $EC, $0, $0, $C, $FD
	dc.b $C, $4, $0, $D, $FD
	dc.b $F4, $2, $0, $F, $D
DATAY6NUGB0H0S_20: dc.b $4
	dc.b $F1, $E, $0, $0, $ED
	dc.b $9, $C, $0, $C, $F5
	dc.b $E9, $0, $0, $10, $FD
	dc.b $F1, $2, $0, $11, $D
DATAY6NUGB0H0S_21: dc.b $4
	dc.b $EC, $5, $0, $0, $6
	dc.b $F4, $A, $0, $4, $EE
	dc.b $FC, $2, $0, $D, $6
	dc.b $4, $1, $0, $10, $E
DATAY6NUGB0H0S_22: dc.b $2
	dc.b $F5, $E, $0, $0, $EF
	dc.b $FD, $1, $0, $C, $F
DATAY6NUGB0H0S_23: dc.b $2
	dc.b $F5, $E, $0, $0, $ED
	dc.b $F5, $2, $0, $C, $D
DATAY6NUGB0H0S_24: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $4, $0, $6, $F3
	dc.b $F5, $4, $0, $8, $EB
	dc.b $F5, $A, $0, $A, $FB
	dc.b $D, $0, $0, $13, $FB
	dc.b $FD, $0, $0, $14, $13
DATAY6NUGB0H0S_25: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $E4, $8, $0, $6, $F4
	dc.b $EC, $4, $0, $9, $FC
	dc.b $F4, $4, $0, $B, $EC
	dc.b $F4, $A, $0, $D, $FC
	dc.b $C, $0, $0, $16, $FC
DATAY6NUGB0H0S_26: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $F3, $4, $0, $6, $ED
	dc.b $EB, $A, $0, $8, $FD
	dc.b $3, $4, $0, $11, $FD
DATAY6NUGB0H0S_27: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $8, $0, $6, $F3
	dc.b $F5, $4, $0, $9, $EB
	dc.b $F5, $D, $0, $B, $FB
	dc.b $5, $8, $0, $13, $FB
DATAY6NUGB0H0S_28: dc.b $4
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
DATAY6NUGB0H0S_29: dc.b $5
	dc.b $FB, $6, $0, $0, $ED
	dc.b $EB, $A, $0, $6, $FD
	dc.b $F3, $4, $0, $F, $ED
	dc.b $3, $4, $0, $11, $FD
	dc.b $B, $0, $0, $13, $FD
DATAY6NUGB0H0S_2C: dc.b $3
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $8, $0, $C, $EC
	dc.b $EE, $8, $0, $F, $F4
DATAY6NUGB0H0S_2D: dc.b $3
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $8, $0, $C, $EC
	dc.b $EE, $8, $0, $F, $F4
DATAY6NUGB0H0S_2E: dc.b $3
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $8, $0, $C, $EC
	dc.b $EE, $8, $0, $F, $F4
DATAY6NUGB0H0S_2F: dc.b $3
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $8, $0, $C, $EC
	dc.b $EE, $8, $0, $F, $F4
DATAY6NUGB0H0S_30: dc.b $3
	dc.b $EE, $F, $0, $0, $EF
	dc.b $E6, $4, $0, $10, $F7
	dc.b $E, $0, $0, $12, $FF
DATAY6NUGB0H0S_31: dc.b $3
	dc.b $EE, $F, $0, $0, $EF
	dc.b $E6, $4, $0, $10, $F7
	dc.b $E, $0, $0, $12, $FF
DATAY6NUGB0H0S_32: dc.b $3
	dc.b $EE, $F, $0, $0, $EF
	dc.b $E6, $4, $0, $10, $F7
	dc.b $E, $0, $0, $12, $FF
DATAY6NUGB0H0S_33: dc.b $3
	dc.b $EE, $F, $0, $0, $EF
	dc.b $E6, $4, $0, $10, $F7
	dc.b $E, $0, $0, $12, $FF
DATAY6NUGB0H0S_34: dc.b $3
	dc.b $F5, $E, $0, $0, $EE
	dc.b $D, $C, $0, $C, $F6
	dc.b $FD, $1, $0, $10, $E
DATAY6NUGB0H0S_35: dc.b $3
	dc.b $F5, $E, $0, $0, $EE
	dc.b $D, $C, $0, $C, $F6
	dc.b $FD, $1, $0, $10, $E
DATAY6NUGB0H0S_36: dc.b $3
	dc.b $F5, $E, $0, $0, $EE
	dc.b $D, $C, $0, $C, $F6
	dc.b $FD, $1, $0, $10, $E
DATAY6NUGB0H0S_37: dc.b $3
	dc.b $F5, $E, $0, $0, $EE
	dc.b $D, $C, $0, $C, $F6
	dc.b $FD, $1, $0, $10, $E
DATAY6NUGB0H0S_38: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATAY6NUGB0H0S_39: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAY6NUGB0H0S_3A: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATAY6NUGB0H0S_3B: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAY6NUGB0H0S_3C: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAY6NUGB0H0S_3D: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAY6NUGB0H0S_3E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAY6NUGB0H0S_3F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAY6NUGB0H0S_40: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAY6NUGB0H0S_41: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F8
	dc.b $4, $0, $0, $F, $8
DATAY6NUGB0H0S_42: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F8
	dc.b $4, $0, $0, $F, $8
DATAY6NUGB0H0S_43: dc.b $3
	dc.b $EC, $B, $0, $0, $F1
	dc.b $FC, $0, $0, $C, $E9
	dc.b $C, $4, $0, $D, $F9
DATAY6NUGB0H0S_44: dc.b $2
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
DATAY6NUGB0H0S_45: dc.b $1
	dc.b $F4, $B, $0, $0, $F8
DATAY6NUGB0H0S_46: dc.b $2
	dc.b $4, $D, $0, $0, $F2
	dc.b $FC, $8, $0, $8, $FA
DATAY6NUGB0H0S_47: dc.b $3
	dc.b $EC, $B, $0, $0, $F8
	dc.b $F4, $6, $0, $C, $E8
	dc.b $C, $4, $0, $12, $F0
DATAY6NUGB0H0S_48: dc.b $2
	dc.b $ED, $E, $0, $0, $F0
	dc.b $5, $9, $0, $C, $F0
DATAY6NUGB0H0S_49: dc.b $2
	dc.b $F5, $F, $0, $0, $EF
	dc.b $ED, $8, $0, $10, $F7
DATAY6NUGB0H0S_4A: dc.b $3
	dc.b $F4, $F, $0, $0, $EC
	dc.b $EC, $C, $0, $10, $F4
	dc.b $F4, $1, $0, $14, $C
DATAY6NUGB0H0S_4B: dc.b $3
	dc.b $ED, $F, $0, $0, $F4
	dc.b $5, $0, $0, $10, $EC
	dc.b $D, $4, $0, $11, $FC
DATAY6NUGB0H0S_4C: dc.b $3
	dc.b $ED, $A, $0, $0, $F9
	dc.b $F5, $2, $0, $9, $F1
	dc.b $5, $5, $0, $C, $F9
DATAY6NUGB0H0S_4D: dc.b $3
	dc.b $F4, $A, $0, $0, $FC
	dc.b $FC, $5, $0, $9, $EC
	dc.b $4, $0, $0, $D, $E4
DATAY6NUGB0H0S_4E: dc.b $3
	dc.b $4, $C, $0, $0, $EC
	dc.b $F4, $9, $0, $4, $F4
	dc.b $4, $0, $0, $A, $C
DATAY6NUGB0H0S_4F: dc.b $3
	dc.b $4, $C, $0, $0, $EC
	dc.b $F4, $9, $0, $4, $F4
	dc.b $4, $0, $0, $A, $C
DATAY6NUGB0H0S_50: dc.b $3
	dc.b $4, $C, $8, $0, $F4
	dc.b $F4, $9, $8, $4, $F4
	dc.b $4, $0, $8, $A, $EC
DATAY6NUGB0H0S_51: dc.b $3
	dc.b $F4, $A, $8, $0, $EC
	dc.b $FC, $5, $8, $9, $4
	dc.b $4, $0, $8, $D, $14
DATAY6NUGB0H0S_52: dc.b $3
	dc.b $F4, $A, $0, $0, $EC
	dc.b $FC, $1, $0, $9, $4
	dc.b $4, $0, $0, $B, $C
DATAY6NUGB0H0S_53: dc.b $3
	dc.b $4, $C, $0, $0, $EC
	dc.b $F4, $9, $0, $4, $F4
	dc.b $4, $0, $0, $A, $C
DATAY6NUGB0H0S_54: dc.b $3
	dc.b $F4, $A, $8, $0, $FC
	dc.b $FC, $1, $8, $9, $F4
	dc.b $4, $0, $8, $B, $EC
DATAY6NUGB0H0S_55: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $5, $0, $C, $F0
	dc.b $8, $0, $0, $10, $0
DATAY6NUGB0H0S_56: dc.b $2
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $9, $0, $C, $8
DATAY6NUGB0H0S_57: dc.b $2
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $9, $0, $C, $8
DATAY6NUGB0H0S_58: dc.b $2
	dc.b $F, $C, $0, $0, $EB
	dc.b $EF, $B, $0, $4, $F3
DATAY6NUGB0H0S_59: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $4, $0, $C, $F4
DATAY6NUGB0H0S_5A: dc.b $2
	dc.b $F, $C, $0, $0, $EB
	dc.b $EF, $B, $0, $4, $F3
DATAY6NUGB0H0S_5B: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $4, $0, $C, $F4
DATAY6NUGB0H0S_5C: dc.b $2
	dc.b $F0, $F, $0, $0, $F4
	dc.b $E8, $4, $0, $10, $FC
DATAY6NUGB0H0S_5D: dc.b $2
	dc.b $F0, $F, $0, $0, $F4
	dc.b $E8, $4, $0, $10, $FC
DATAY6NUGB0H0S_5E: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $8, $8, $0, $C, $F4
	dc.b $0, $0, $0, $F, $C
DATAY6NUGB0H0S_5F: dc.b $5
	dc.b $FB, $D, $0, $0, $EC
	dc.b $EB, $9, $0, $8, $F4
	dc.b $B, $C, $0, $E, $F4
	dc.b $F3, $0, $0, $12, $C
	dc.b $3, $0, $0, $13, $C
DATAY6NUGB0H0S_60: dc.b $3
	dc.b $F4, $D, $0, $0, $ED
	dc.b $EC, $8, $0, $8, $F5
	dc.b $4, $9, $0, $B, $F5
DATAY6NUGB0H0S_61: dc.b $3
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
	dc.b $4, $0, $0, $10, $9
DATAY6NUGB0H0S_62: dc.b $3
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
	dc.b $2, $0, $0, $10, $9
DATAY6NUGB0H0S_63: dc.b $3
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
	dc.b $FF, $0, $0, $10, $9
	even