; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Feb 18 2021 11:38:49 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA3KNVU9H9VQ6:
	dc.w $0, DATA3KNVU9H9VQ6_1-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_2-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_3-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_4-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_5-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_6-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_7-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_8-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_9-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_A-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_B-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_C-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_D-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_E-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_F-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_10-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_11-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_12-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_13-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_14-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_15-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_16-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_17-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_18-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_19-DATA3KNVU9H9VQ6
	dc.w $0, $0
	dc.w DATA3KNVU9H9VQ6_1C-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_1D-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_1E-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_1F-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_20-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_21-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_22-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_23-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_24-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_25-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_26-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_27-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_28-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_29-DATA3KNVU9H9VQ6
	dc.w $0, $0
	dc.w DATA3KNVU9H9VQ6_2C-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_2D-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_2E-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_2F-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_30-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_31-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_32-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_33-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_34-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_35-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_36-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_37-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_38-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_39-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_3A-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_3B-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_3C-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_3D-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_3E-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_3F-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_40-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_41-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_42-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_43-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_44-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_45-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_46-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_47-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_48-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_49-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_4A-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_4B-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_4C-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_4D-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_4E-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_4F-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_50-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_51-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_52-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_53-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_54-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_55-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_56-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_57-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_58-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_59-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_5A-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_5B-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_5C-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_5D-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_5E-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_5F-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_60-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_61-DATA3KNVU9H9VQ6
	dc.w DATA3KNVU9H9VQ6_62-DATA3KNVU9H9VQ6, DATA3KNVU9H9VQ6_63-DATA3KNVU9H9VQ6
DATA3KNVU9H9VQ6_1: dc.b $2
	dc.b $ED, $B, $0, $0, $F2
	dc.b $D, $C, $0, $C, $F2
DATA3KNVU9H9VQ6_2: dc.b $2
	dc.b $ED, $B, $0, $0, $F2
	dc.b $D, $C, $0, $C, $F2
DATA3KNVU9H9VQ6_3: dc.b $2
	dc.b $ED, $B, $0, $0, $F2
	dc.b $D, $C, $0, $C, $F2
DATA3KNVU9H9VQ6_4: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATA3KNVU9H9VQ6_5: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATA3KNVU9H9VQ6_6: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATA3KNVU9H9VQ6_7: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATA3KNVU9H9VQ6_8: dc.b $2
	dc.b $ED, $B, $0, $0, $F2
	dc.b $D, $C, $0, $C, $F2
DATA3KNVU9H9VQ6_9: dc.b $2
	dc.b $ED, $B, $0, $0, $F4
	dc.b $D, $8, $0, $C, $F4
DATA3KNVU9H9VQ6_A: dc.b $2
	dc.b $EE, $A, $0, $0, $EF
	dc.b $6, $9, $0, $9, $F7
DATA3KNVU9H9VQ6_B: dc.b $2
	dc.b $EC, $A, $0, $0, $EE
	dc.b $4, $9, $0, $9, $F6
DATA3KNVU9H9VQ6_C: dc.b $3
	dc.b $C, $C, $0, $0, $EB
	dc.b $EC, $B, $0, $4, $F3
	dc.b $FC, $2, $0, $10, $B
DATA3KNVU9H9VQ6_D: dc.b $4
	dc.b $5, $5, $0, $0, $EB
	dc.b $ED, $A, $0, $4, $F3
	dc.b $5, $4, $0, $D, $FB
	dc.b $D, $4, $0, $F, $3
DATA3KNVU9H9VQ6_E: dc.b $2
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $8, $0, $C, $F3
DATA3KNVU9H9VQ6_F: dc.b $4
	dc.b $FC, $C, $0, $0, $EC
	dc.b $EC, $9, $0, $4, $F4
	dc.b $4, $9, $0, $A, $F4
	dc.b $FC, $1, $0, $10, $C
DATA3KNVU9H9VQ6_10: dc.b $3
	dc.b $F4, $F, $0, $0, $F0
	dc.b $EC, $8, $0, $10, $F8
	dc.b $FC, $0, $0, $13, $10
DATA3KNVU9H9VQ6_11: dc.b $4
	dc.b $5, $5, $0, $0, $ED
	dc.b $ED, $A, $0, $4, $F5
	dc.b $5, $8, $0, $D, $FD
	dc.b $D, $4, $0, $10, $5
DATA3KNVU9H9VQ6_12: dc.b $2
	dc.b $EE, $B, $0, $0, $F4
	dc.b $E, $4, $0, $C, $F4
DATA3KNVU9H9VQ6_13: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATA3KNVU9H9VQ6_14: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $6, $0, $6, $3
	dc.b $FB, $8, $0, $C, $EB
	dc.b $3, $9, $0, $F, $F3
	dc.b $13, $0, $0, $15, $FB
DATA3KNVU9H9VQ6_15: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
DATA3KNVU9H9VQ6_16: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
DATA3KNVU9H9VQ6_17: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
DATA3KNVU9H9VQ6_18: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
DATA3KNVU9H9VQ6_19: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
DATA3KNVU9H9VQ6_1C: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $ED, $8, $0, $C, $FC
	dc.b $F5, $3, $0, $F, $C
DATA3KNVU9H9VQ6_1D: dc.b $4
	dc.b $F5, $E, $0, $0, $ED
	dc.b $D, $4, $0, $C, $5
	dc.b $ED, $1, $0, $E, $D
	dc.b $5, $0, $0, $10, $D
DATA3KNVU9H9VQ6_1E: dc.b $2
	dc.b $F6, $E, $0, $0, $EE
	dc.b $F6, $2, $0, $C, $E
DATA3KNVU9H9VQ6_1F: dc.b $4
	dc.b $F4, $E, $0, $0, $ED
	dc.b $EC, $0, $0, $C, $FD
	dc.b $C, $4, $0, $D, $FD
	dc.b $F4, $2, $0, $F, $D
DATA3KNVU9H9VQ6_20: dc.b $4
	dc.b $F1, $E, $0, $0, $ED
	dc.b $9, $C, $0, $C, $F5
	dc.b $E9, $0, $0, $10, $FD
	dc.b $F1, $2, $0, $11, $D
DATA3KNVU9H9VQ6_21: dc.b $4
	dc.b $EC, $5, $0, $0, $6
	dc.b $F4, $A, $0, $4, $EE
	dc.b $FC, $2, $0, $D, $6
	dc.b $4, $1, $0, $10, $E
DATA3KNVU9H9VQ6_22: dc.b $2
	dc.b $F5, $E, $0, $0, $EF
	dc.b $FD, $1, $0, $C, $F
DATA3KNVU9H9VQ6_23: dc.b $2
	dc.b $F5, $E, $0, $0, $ED
	dc.b $F5, $2, $0, $C, $D
DATA3KNVU9H9VQ6_24: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $4, $0, $6, $F3
	dc.b $F5, $4, $0, $8, $EB
	dc.b $F5, $A, $0, $A, $FB
	dc.b $D, $0, $0, $13, $FB
	dc.b $FD, $0, $0, $14, $13
DATA3KNVU9H9VQ6_25: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $E4, $8, $0, $6, $F4
	dc.b $EC, $4, $0, $9, $FC
	dc.b $F4, $4, $0, $B, $EC
	dc.b $F4, $A, $0, $D, $FC
	dc.b $C, $0, $0, $16, $FC
DATA3KNVU9H9VQ6_26: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $F3, $4, $0, $6, $ED
	dc.b $EB, $A, $0, $8, $FD
	dc.b $3, $4, $0, $11, $FD
DATA3KNVU9H9VQ6_27: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $8, $0, $6, $F3
	dc.b $F5, $4, $0, $9, $EB
	dc.b $F5, $D, $0, $B, $FB
	dc.b $5, $8, $0, $13, $FB
DATA3KNVU9H9VQ6_28: dc.b $4
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
DATA3KNVU9H9VQ6_29: dc.b $5
	dc.b $FB, $6, $0, $0, $ED
	dc.b $EB, $A, $0, $6, $FD
	dc.b $F3, $4, $0, $F, $ED
	dc.b $3, $4, $0, $11, $FD
	dc.b $B, $0, $0, $13, $FD
DATA3KNVU9H9VQ6_2C: dc.b $3
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $8, $0, $C, $EC
	dc.b $EE, $8, $0, $F, $F4
DATA3KNVU9H9VQ6_2D: dc.b $3
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $8, $0, $C, $EC
	dc.b $EE, $8, $0, $F, $F4
DATA3KNVU9H9VQ6_2E: dc.b $3
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $8, $0, $C, $EC
	dc.b $EE, $8, $0, $F, $F4
DATA3KNVU9H9VQ6_2F: dc.b $3
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $8, $0, $C, $EC
	dc.b $EE, $8, $0, $F, $F4
DATA3KNVU9H9VQ6_30: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATA3KNVU9H9VQ6_31: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATA3KNVU9H9VQ6_32: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATA3KNVU9H9VQ6_33: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATA3KNVU9H9VQ6_34: dc.b $3
	dc.b $F5, $E, $0, $0, $EE
	dc.b $D, $C, $0, $C, $F6
	dc.b $FD, $1, $0, $10, $E
DATA3KNVU9H9VQ6_35: dc.b $3
	dc.b $F5, $E, $0, $0, $EE
	dc.b $D, $C, $0, $C, $F6
	dc.b $FD, $1, $0, $10, $E
DATA3KNVU9H9VQ6_36: dc.b $3
	dc.b $F5, $E, $0, $0, $EE
	dc.b $D, $C, $0, $C, $F6
	dc.b $FD, $1, $0, $10, $E
DATA3KNVU9H9VQ6_37: dc.b $3
	dc.b $F5, $E, $0, $0, $EE
	dc.b $D, $C, $0, $C, $F6
	dc.b $FD, $1, $0, $10, $E
DATA3KNVU9H9VQ6_38: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATA3KNVU9H9VQ6_39: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATA3KNVU9H9VQ6_3A: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATA3KNVU9H9VQ6_3B: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATA3KNVU9H9VQ6_3C: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA3KNVU9H9VQ6_3D: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA3KNVU9H9VQ6_3E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA3KNVU9H9VQ6_3F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA3KNVU9H9VQ6_40: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA3KNVU9H9VQ6_41: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F8
	dc.b $4, $0, $0, $F, $8
DATA3KNVU9H9VQ6_42: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F8
	dc.b $4, $0, $0, $F, $8
DATA3KNVU9H9VQ6_43: dc.b $3
	dc.b $EC, $B, $0, $0, $F1
	dc.b $FC, $0, $0, $C, $E9
	dc.b $C, $4, $0, $D, $F9
DATA3KNVU9H9VQ6_44: dc.b $2
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
DATA3KNVU9H9VQ6_45: dc.b $1
	dc.b $F4, $B, $0, $0, $F8
DATA3KNVU9H9VQ6_46: dc.b $2
	dc.b $4, $D, $0, $0, $F2
	dc.b $FC, $8, $0, $8, $FA
DATA3KNVU9H9VQ6_47: dc.b $3
	dc.b $EC, $B, $0, $0, $F8
	dc.b $F4, $6, $0, $C, $E8
	dc.b $C, $4, $0, $12, $F0
DATA3KNVU9H9VQ6_48: dc.b $2
	dc.b $ED, $E, $0, $0, $F0
	dc.b $5, $9, $0, $C, $F0
DATA3KNVU9H9VQ6_49: dc.b $2
	dc.b $F5, $F, $0, $0, $EF
	dc.b $ED, $8, $0, $10, $F7
DATA3KNVU9H9VQ6_4A: dc.b $3
	dc.b $F4, $F, $0, $0, $EC
	dc.b $EC, $C, $0, $10, $F4
	dc.b $F4, $1, $0, $14, $C
DATA3KNVU9H9VQ6_4B: dc.b $3
	dc.b $ED, $F, $0, $0, $F4
	dc.b $5, $0, $0, $10, $EC
	dc.b $D, $4, $0, $11, $FC
DATA3KNVU9H9VQ6_4C: dc.b $3
	dc.b $ED, $A, $0, $0, $F9
	dc.b $F5, $2, $0, $9, $F1
	dc.b $5, $5, $0, $C, $F9
DATA3KNVU9H9VQ6_4D: dc.b $3
	dc.b $F4, $A, $0, $0, $FC
	dc.b $FC, $5, $0, $9, $EC
	dc.b $4, $0, $0, $D, $E4
DATA3KNVU9H9VQ6_4E: dc.b $3
	dc.b $4, $C, $0, $0, $EC
	dc.b $F4, $9, $0, $4, $F4
	dc.b $4, $0, $0, $A, $C
DATA3KNVU9H9VQ6_4F: dc.b $3
	dc.b $4, $C, $0, $0, $EC
	dc.b $F4, $9, $0, $4, $F4
	dc.b $4, $0, $0, $A, $C
DATA3KNVU9H9VQ6_50: dc.b $3
	dc.b $4, $C, $8, $0, $F4
	dc.b $F4, $9, $8, $4, $F4
	dc.b $4, $0, $8, $A, $EC
DATA3KNVU9H9VQ6_51: dc.b $3
	dc.b $F4, $A, $8, $0, $EC
	dc.b $FC, $5, $8, $9, $4
	dc.b $4, $0, $8, $D, $14
DATA3KNVU9H9VQ6_52: dc.b $3
	dc.b $F4, $A, $0, $0, $EC
	dc.b $FC, $1, $0, $9, $4
	dc.b $4, $0, $0, $B, $C
DATA3KNVU9H9VQ6_53: dc.b $3
	dc.b $4, $C, $0, $0, $EC
	dc.b $F4, $9, $0, $4, $F4
	dc.b $4, $0, $0, $A, $C
DATA3KNVU9H9VQ6_54: dc.b $3
	dc.b $F4, $A, $8, $0, $FC
	dc.b $FC, $1, $8, $9, $F4
	dc.b $4, $0, $8, $B, $EC
DATA3KNVU9H9VQ6_55: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $5, $0, $C, $F0
	dc.b $8, $0, $0, $10, $0
DATA3KNVU9H9VQ6_56: dc.b $2
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $9, $0, $C, $8
DATA3KNVU9H9VQ6_57: dc.b $2
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $9, $0, $C, $8
DATA3KNVU9H9VQ6_58: dc.b $2
	dc.b $F, $C, $0, $0, $EB
	dc.b $EF, $B, $0, $4, $F3
DATA3KNVU9H9VQ6_59: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $4, $0, $C, $F4
DATA3KNVU9H9VQ6_5A: dc.b $2
	dc.b $F, $C, $0, $0, $EB
	dc.b $EF, $B, $0, $4, $F3
DATA3KNVU9H9VQ6_5B: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $4, $0, $C, $F4
DATA3KNVU9H9VQ6_5C: dc.b $2
	dc.b $F0, $F, $0, $0, $F4
	dc.b $E8, $4, $0, $10, $FC
DATA3KNVU9H9VQ6_5D: dc.b $2
	dc.b $F0, $F, $0, $0, $F4
	dc.b $E8, $4, $0, $10, $FC
DATA3KNVU9H9VQ6_5E: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $8, $8, $0, $C, $F4
	dc.b $0, $0, $0, $F, $C
DATA3KNVU9H9VQ6_5F: dc.b $5
	dc.b $FB, $D, $0, $0, $EC
	dc.b $EB, $9, $0, $8, $F4
	dc.b $B, $C, $0, $E, $F4
	dc.b $F3, $0, $0, $12, $C
	dc.b $3, $0, $0, $13, $C
DATA3KNVU9H9VQ6_60: dc.b $3
	dc.b $F4, $D, $0, $0, $ED
	dc.b $EC, $8, $0, $8, $F5
	dc.b $4, $9, $0, $B, $F5
DATA3KNVU9H9VQ6_61: dc.b $3
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
	dc.b $4, $0, $0, $10, $9
DATA3KNVU9H9VQ6_62: dc.b $3
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
	dc.b $2, $0, $0, $10, $9
DATA3KNVU9H9VQ6_63: dc.b $3
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
	dc.b $FF, $0, $0, $10, $9
	even