; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Feb 18 2021 17:19:23 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA67XB17S4UC8:
	dc.w $0, DATA67XB17S4UC8_1-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_2-DATA67XB17S4UC8, DATA67XB17S4UC8_3-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_4-DATA67XB17S4UC8, DATA67XB17S4UC8_5-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_6-DATA67XB17S4UC8, DATA67XB17S4UC8_7-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_8-DATA67XB17S4UC8, DATA67XB17S4UC8_9-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_A-DATA67XB17S4UC8, DATA67XB17S4UC8_B-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_C-DATA67XB17S4UC8, DATA67XB17S4UC8_D-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_E-DATA67XB17S4UC8, DATA67XB17S4UC8_F-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_10-DATA67XB17S4UC8, DATA67XB17S4UC8_11-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_12-DATA67XB17S4UC8, DATA67XB17S4UC8_13-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_14-DATA67XB17S4UC8, DATA67XB17S4UC8_15-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_16-DATA67XB17S4UC8, DATA67XB17S4UC8_17-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_18-DATA67XB17S4UC8, DATA67XB17S4UC8_19-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_1A-DATA67XB17S4UC8, DATA67XB17S4UC8_1B-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_1C-DATA67XB17S4UC8, DATA67XB17S4UC8_1D-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_1E-DATA67XB17S4UC8, DATA67XB17S4UC8_1F-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_20-DATA67XB17S4UC8, DATA67XB17S4UC8_21-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_22-DATA67XB17S4UC8, DATA67XB17S4UC8_23-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_24-DATA67XB17S4UC8, DATA67XB17S4UC8_25-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_26-DATA67XB17S4UC8, DATA67XB17S4UC8_27-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_28-DATA67XB17S4UC8, DATA67XB17S4UC8_29-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_2A-DATA67XB17S4UC8, DATA67XB17S4UC8_2B-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_2C-DATA67XB17S4UC8, DATA67XB17S4UC8_2D-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_2E-DATA67XB17S4UC8, DATA67XB17S4UC8_2F-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_30-DATA67XB17S4UC8, DATA67XB17S4UC8_31-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_32-DATA67XB17S4UC8, DATA67XB17S4UC8_33-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_34-DATA67XB17S4UC8, DATA67XB17S4UC8_35-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_36-DATA67XB17S4UC8, DATA67XB17S4UC8_37-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_38-DATA67XB17S4UC8, DATA67XB17S4UC8_39-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_3A-DATA67XB17S4UC8, DATA67XB17S4UC8_3B-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_3C-DATA67XB17S4UC8, DATA67XB17S4UC8_3D-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_3E-DATA67XB17S4UC8, DATA67XB17S4UC8_3F-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_40-DATA67XB17S4UC8, DATA67XB17S4UC8_41-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_42-DATA67XB17S4UC8, DATA67XB17S4UC8_43-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_44-DATA67XB17S4UC8, DATA67XB17S4UC8_45-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_46-DATA67XB17S4UC8, DATA67XB17S4UC8_47-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_48-DATA67XB17S4UC8, DATA67XB17S4UC8_49-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_4A-DATA67XB17S4UC8, DATA67XB17S4UC8_4B-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_4C-DATA67XB17S4UC8, DATA67XB17S4UC8_4D-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_4E-DATA67XB17S4UC8, DATA67XB17S4UC8_4F-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_50-DATA67XB17S4UC8, DATA67XB17S4UC8_51-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_52-DATA67XB17S4UC8, DATA67XB17S4UC8_53-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_54-DATA67XB17S4UC8, DATA67XB17S4UC8_55-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_56-DATA67XB17S4UC8, DATA67XB17S4UC8_57-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_58-DATA67XB17S4UC8, DATA67XB17S4UC8_59-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_5A-DATA67XB17S4UC8, DATA67XB17S4UC8_5B-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_5C-DATA67XB17S4UC8, DATA67XB17S4UC8_5D-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_5E-DATA67XB17S4UC8, DATA67XB17S4UC8_5F-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_60-DATA67XB17S4UC8, DATA67XB17S4UC8_61-DATA67XB17S4UC8
	dc.w DATA67XB17S4UC8_62-DATA67XB17S4UC8, DATA67XB17S4UC8_63-DATA67XB17S4UC8
DATA67XB17S4UC8_1: dc.b $2
	dc.b $ED, $B, $0, $0, $F2
	dc.b $D, $C, $0, $C, $F2
DATA67XB17S4UC8_2: dc.b $2
	dc.b $ED, $B, $0, $0, $F2
	dc.b $D, $C, $0, $C, $F2
DATA67XB17S4UC8_3: dc.b $2
	dc.b $ED, $B, $0, $0, $F2
	dc.b $D, $C, $0, $C, $F2
DATA67XB17S4UC8_4: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATA67XB17S4UC8_5: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATA67XB17S4UC8_6: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATA67XB17S4UC8_7: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATA67XB17S4UC8_8: dc.b $2
	dc.b $ED, $B, $0, $0, $F2
	dc.b $D, $C, $0, $C, $F2
DATA67XB17S4UC8_9: dc.b $2
	dc.b $ED, $B, $0, $0, $F4
	dc.b $D, $8, $0, $C, $F4
DATA67XB17S4UC8_A: dc.b $2
	dc.b $EE, $A, $0, $0, $EF
	dc.b $6, $9, $0, $9, $F7
DATA67XB17S4UC8_B: dc.b $2
	dc.b $EC, $A, $0, $0, $EE
	dc.b $4, $9, $0, $9, $F6
DATA67XB17S4UC8_C: dc.b $3
	dc.b $C, $C, $0, $0, $EB
	dc.b $EC, $B, $0, $4, $F3
	dc.b $FC, $2, $0, $10, $B
DATA67XB17S4UC8_D: dc.b $4
	dc.b $5, $5, $0, $0, $EB
	dc.b $ED, $A, $0, $4, $F3
	dc.b $5, $4, $0, $D, $FB
	dc.b $D, $4, $0, $F, $3
DATA67XB17S4UC8_E: dc.b $2
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $8, $0, $C, $F3
DATA67XB17S4UC8_F: dc.b $4
	dc.b $FC, $C, $0, $0, $EC
	dc.b $EC, $9, $0, $4, $F4
	dc.b $4, $9, $0, $A, $F4
	dc.b $FC, $1, $0, $10, $C
DATA67XB17S4UC8_10: dc.b $3
	dc.b $F4, $F, $0, $0, $F0
	dc.b $EC, $8, $0, $10, $F8
	dc.b $FC, $0, $0, $13, $10
DATA67XB17S4UC8_11: dc.b $4
	dc.b $5, $5, $0, $0, $ED
	dc.b $ED, $A, $0, $4, $F5
	dc.b $5, $8, $0, $D, $FD
	dc.b $D, $4, $0, $10, $5
DATA67XB17S4UC8_12: dc.b $2
	dc.b $EE, $B, $0, $0, $F4
	dc.b $E, $4, $0, $C, $F4
DATA67XB17S4UC8_13: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATA67XB17S4UC8_14: dc.b $5
	dc.b $F2, $D, $0, $0, $EB
	dc.b $EA, $4, $0, $8, $F3
	dc.b $2, $C, $0, $A, $F3
	dc.b $A, $5, $0, $E, $FB
	dc.b $FA, $4, $0, $12, $B
DATA67XB17S4UC8_15: dc.b $5
	dc.b $EE, $9, $0, $0, $EB
	dc.b $F6, $2, $0, $6, $3
	dc.b $FE, $4, $0, $9, $F3
	dc.b $FE, $5, $0, $B, $B
	dc.b $6, $1, $0, $F, $FB
DATA67XB17S4UC8_16: dc.b $4
	dc.b $F5, $C, $0, $0, $EC
	dc.b $ED, $4, $0, $4, $F4
	dc.b $FD, $C, $0, $6, $F4
	dc.b $5, $9, $0, $A, $FC
DATA67XB17S4UC8_17: dc.b $6
	dc.b $EC, $A, $0, $0, $ED
	dc.b $4, $C, $0, $9, $F5
	dc.b $C, $4, $0, $D, $FD
	dc.b $F4, $1, $0, $F, $5
	dc.b $14, $0, $0, $11, $5
	dc.b $FC, $0, $0, $12, $D
DATA67XB17S4UC8_18: dc.b $5
	dc.b $EB, $A, $0, $0, $EC
	dc.b $3, $9, $0, $9, $F4
	dc.b $13, $4, $0, $F, $FC
	dc.b $F3, $5, $0, $11, $4
	dc.b $3, $0, $0, $15, $C
DATA67XB17S4UC8_19: dc.b $5
	dc.b $EE, $A, $0, $0, $EE
	dc.b $E6, $0, $0, $9, $F6
	dc.b $6, $5, $0, $A, $F6
	dc.b $F6, $9, $0, $E, $6
	dc.b $6, $0, $0, $14, $6
DATA67XB17S4UC8_1A: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATA67XB17S4UC8_1B: dc.b $6
	dc.b $F3, $C, $0, $0, $EB
	dc.b $EB, $4, $0, $4, $F3
	dc.b $FB, $C, $0, $6, $F3
	dc.b $3, $5, $0, $A, $FB
	dc.b $13, $0, $0, $E, $3
	dc.b $3, $0, $0, $F, $B
DATA67XB17S4UC8_1C: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $ED, $8, $0, $C, $FC
	dc.b $F5, $3, $0, $F, $C
DATA67XB17S4UC8_1D: dc.b $4
	dc.b $F5, $E, $0, $0, $ED
	dc.b $D, $4, $0, $C, $5
	dc.b $ED, $1, $0, $E, $D
	dc.b $5, $0, $0, $10, $D
DATA67XB17S4UC8_1E: dc.b $2
	dc.b $F6, $E, $0, $0, $EE
	dc.b $F6, $2, $0, $C, $E
DATA67XB17S4UC8_1F: dc.b $4
	dc.b $F4, $E, $0, $0, $ED
	dc.b $EC, $0, $0, $C, $FD
	dc.b $C, $4, $0, $D, $FD
	dc.b $F4, $2, $0, $F, $D
DATA67XB17S4UC8_20: dc.b $4
	dc.b $F1, $E, $0, $0, $ED
	dc.b $9, $C, $0, $C, $F5
	dc.b $E9, $0, $0, $10, $FD
	dc.b $F1, $2, $0, $11, $D
DATA67XB17S4UC8_21: dc.b $4
	dc.b $EC, $5, $0, $0, $6
	dc.b $F4, $A, $0, $4, $EE
	dc.b $FC, $2, $0, $D, $6
	dc.b $4, $1, $0, $10, $E
DATA67XB17S4UC8_22: dc.b $2
	dc.b $F5, $E, $0, $0, $EF
	dc.b $FD, $1, $0, $C, $F
DATA67XB17S4UC8_23: dc.b $2
	dc.b $F5, $E, $0, $0, $ED
	dc.b $F5, $2, $0, $C, $D
DATA67XB17S4UC8_24: dc.b $6
	dc.b $E5, $3, $0, $0, $FA
	dc.b $ED, $3, $0, $4, $2
	dc.b $F5, $3, $0, $8, $F2
	dc.b $F5, $5, $0, $C, $A
	dc.b $FD, $1, $0, $10, $EA
	dc.b $5, $1, $0, $12, $FA
DATA67XB17S4UC8_25: dc.b $5
	dc.b $FD, $9, $0, $0, $EE
	dc.b $D, $4, $0, $6, $EE
	dc.b $F5, $8, $0, $8, $F6
	dc.b $E5, $5, $0, $B, $FE
	dc.b $FD, $4, $0, $F, $6
DATA67XB17S4UC8_26: dc.b $4
	dc.b $EC, $A, $0, $0, $FD
	dc.b $F4, $3, $0, $9, $F5
	dc.b $FC, $1, $0, $D, $ED
	dc.b $4, $0, $0, $F, $FD
DATA67XB17S4UC8_27: dc.b $6
	dc.b $FB, $A, $0, $0, $EC
	dc.b $F3, $C, $0, $9, $F4
	dc.b $EB, $4, $0, $D, $FC
	dc.b $FB, $4, $0, $F, $4
	dc.b $3, $0, $0, $11, $4
	dc.b $F3, $0, $0, $12, $14
DATA67XB17S4UC8_28: dc.b $5
	dc.b $FC, $A, $0, $0, $EB
	dc.b $EC, $9, $0, $9, $F3
	dc.b $FC, $5, $0, $F, $3
	dc.b $F4, $4, $0, $13, $B
	dc.b $FC, $0, $0, $15, $13
DATA67XB17S4UC8_29: dc.b $5
	dc.b $FA, $D, $0, $0, $E8
	dc.b $A, $8, $0, $8, $F0
	dc.b $E2, $6, $0, $B, $F8
	dc.b $F2, $2, $0, $11, $8
	dc.b $FA, $0, $0, $14, $10
DATA67XB17S4UC8_2A: dc.b $4
	dc.b $F8, $A, $0, $0, $EC
	dc.b $F0, $8, $0, $9, $FC
	dc.b $F8, $4, $0, $C, $4
	dc.b $0, $0, $0, $E, $4
DATA67XB17S4UC8_2B: dc.b $6
	dc.b $FD, $9, $0, $0, $EB
	dc.b $F5, $C, $0, $6, $F3
	dc.b $D, $0, $0, $A, $F3
	dc.b $ED, $4, $0, $B, $FB
	dc.b $FD, $4, $0, $D, $3
	dc.b $F5, $0, $0, $F, $13
DATA67XB17S4UC8_2C: dc.b $3
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $8, $0, $C, $EC
	dc.b $EE, $8, $0, $F, $F4
DATA67XB17S4UC8_2D: dc.b $3
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $8, $0, $C, $EC
	dc.b $EE, $8, $0, $F, $F4
DATA67XB17S4UC8_2E: dc.b $3
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $8, $0, $C, $EC
	dc.b $EE, $8, $0, $F, $F4
DATA67XB17S4UC8_2F: dc.b $3
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $8, $0, $C, $EC
	dc.b $EE, $8, $0, $F, $F4
DATA67XB17S4UC8_30: dc.b $3
	dc.b $EE, $F, $0, $0, $EF
	dc.b $E6, $4, $0, $10, $F7
	dc.b $E, $0, $0, $12, $FF
DATA67XB17S4UC8_31: dc.b $3
	dc.b $EE, $F, $0, $0, $EF
	dc.b $E6, $4, $0, $10, $F7
	dc.b $E, $0, $0, $12, $FF
DATA67XB17S4UC8_32: dc.b $3
	dc.b $EE, $F, $0, $0, $EF
	dc.b $E6, $4, $0, $10, $F7
	dc.b $E, $0, $0, $12, $FF
DATA67XB17S4UC8_33: dc.b $3
	dc.b $EE, $F, $0, $0, $EF
	dc.b $E6, $4, $0, $10, $F7
	dc.b $E, $0, $0, $12, $FF
DATA67XB17S4UC8_34: dc.b $3
	dc.b $F1, $E, $0, $0, $EE
	dc.b $9, $C, $0, $C, $F6
	dc.b $F9, $1, $0, $10, $E
DATA67XB17S4UC8_35: dc.b $3
	dc.b $F1, $E, $0, $0, $EE
	dc.b $9, $C, $0, $C, $F6
	dc.b $F9, $1, $0, $10, $E
DATA67XB17S4UC8_36: dc.b $3
	dc.b $F1, $E, $0, $0, $EE
	dc.b $9, $C, $0, $C, $F6
	dc.b $F9, $1, $0, $10, $E
DATA67XB17S4UC8_37: dc.b $3
	dc.b $F1, $E, $0, $0, $EE
	dc.b $9, $C, $0, $C, $F6
	dc.b $F9, $1, $0, $10, $E
DATA67XB17S4UC8_38: dc.b $3
	dc.b $F1, $F, $0, $0, $EE
	dc.b $F9, $1, $0, $10, $E6
	dc.b $F9, $0, $0, $12, $E
DATA67XB17S4UC8_39: dc.b $3
	dc.b $F2, $F, $0, $0, $EE
	dc.b $FA, $1, $0, $10, $E6
	dc.b $FA, $0, $0, $12, $E
DATA67XB17S4UC8_3A: dc.b $3
	dc.b $F1, $F, $0, $0, $EE
	dc.b $F9, $1, $0, $10, $E6
	dc.b $F9, $0, $0, $12, $E
DATA67XB17S4UC8_3B: dc.b $3
	dc.b $F2, $F, $0, $0, $EE
	dc.b $FA, $1, $0, $10, $E6
	dc.b $FA, $0, $0, $12, $E
DATA67XB17S4UC8_3C: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA67XB17S4UC8_3D: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA67XB17S4UC8_3E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA67XB17S4UC8_3F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA67XB17S4UC8_40: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA67XB17S4UC8_41: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F8
	dc.b $4, $0, $0, $F, $8
DATA67XB17S4UC8_42: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F8
	dc.b $4, $0, $0, $F, $8
DATA67XB17S4UC8_43: dc.b $3
	dc.b $EC, $B, $0, $0, $F1
	dc.b $FC, $0, $0, $C, $E9
	dc.b $C, $4, $0, $D, $F9
DATA67XB17S4UC8_44: dc.b $2
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
DATA67XB17S4UC8_45: dc.b $1
	dc.b $F4, $B, $0, $0, $F8
DATA67XB17S4UC8_46: dc.b $2
	dc.b $4, $D, $0, $0, $F2
	dc.b $FC, $8, $0, $8, $FA
DATA67XB17S4UC8_47: dc.b $3
	dc.b $EC, $B, $0, $0, $F8
	dc.b $F4, $6, $0, $C, $E8
	dc.b $C, $4, $0, $12, $F0
DATA67XB17S4UC8_48: dc.b $2
	dc.b $ED, $E, $0, $0, $F0
	dc.b $5, $9, $0, $C, $F0
DATA67XB17S4UC8_49: dc.b $2
	dc.b $F5, $F, $0, $0, $EF
	dc.b $ED, $8, $0, $10, $F7
DATA67XB17S4UC8_4A: dc.b $3
	dc.b $F4, $F, $0, $0, $EC
	dc.b $EC, $C, $0, $10, $F4
	dc.b $F4, $1, $0, $14, $C
DATA67XB17S4UC8_4B: dc.b $3
	dc.b $ED, $F, $0, $0, $F4
	dc.b $5, $0, $0, $10, $EC
	dc.b $D, $4, $0, $11, $FC
DATA67XB17S4UC8_4C: dc.b $3
	dc.b $ED, $A, $0, $0, $F9
	dc.b $F5, $2, $0, $9, $F1
	dc.b $5, $5, $0, $C, $F9
DATA67XB17S4UC8_4D: dc.b $3
	dc.b $F4, $A, $0, $0, $FC
	dc.b $FC, $5, $0, $9, $EC
	dc.b $4, $0, $0, $D, $E4
DATA67XB17S4UC8_4E: dc.b $3
	dc.b $4, $C, $0, $0, $EC
	dc.b $F4, $9, $0, $4, $F4
	dc.b $4, $0, $0, $A, $C
DATA67XB17S4UC8_4F: dc.b $3
	dc.b $4, $C, $0, $0, $EC
	dc.b $F4, $9, $0, $4, $F4
	dc.b $4, $0, $0, $A, $C
DATA67XB17S4UC8_50: dc.b $3
	dc.b $4, $C, $8, $0, $F4
	dc.b $F4, $9, $8, $4, $F4
	dc.b $4, $0, $8, $A, $EC
DATA67XB17S4UC8_51: dc.b $3
	dc.b $F4, $A, $8, $0, $EC
	dc.b $FC, $5, $8, $9, $4
	dc.b $4, $0, $8, $D, $14
DATA67XB17S4UC8_52: dc.b $3
	dc.b $F4, $A, $0, $0, $EC
	dc.b $FC, $1, $0, $9, $4
	dc.b $4, $0, $0, $B, $C
DATA67XB17S4UC8_53: dc.b $3
	dc.b $4, $C, $0, $0, $EC
	dc.b $F4, $9, $0, $4, $F4
	dc.b $4, $0, $0, $A, $C
DATA67XB17S4UC8_54: dc.b $3
	dc.b $F4, $A, $8, $0, $FC
	dc.b $FC, $1, $8, $9, $F4
	dc.b $4, $0, $8, $B, $EC
DATA67XB17S4UC8_55: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $5, $0, $C, $F0
	dc.b $8, $0, $0, $10, $0
DATA67XB17S4UC8_56: dc.b $2
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $9, $0, $C, $8
DATA67XB17S4UC8_57: dc.b $2
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $9, $0, $C, $8
DATA67XB17S4UC8_58: dc.b $2
	dc.b $F, $C, $0, $0, $EB
	dc.b $EF, $B, $0, $4, $F3
DATA67XB17S4UC8_59: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $4, $0, $C, $F4
DATA67XB17S4UC8_5A: dc.b $2
	dc.b $F, $C, $0, $0, $EB
	dc.b $EF, $B, $0, $4, $F3
DATA67XB17S4UC8_5B: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $4, $0, $C, $F4
DATA67XB17S4UC8_5C: dc.b $2
	dc.b $F0, $F, $0, $0, $F4
	dc.b $E8, $4, $0, $10, $FC
DATA67XB17S4UC8_5D: dc.b $2
	dc.b $F0, $F, $0, $0, $F4
	dc.b $E8, $4, $0, $10, $FC
DATA67XB17S4UC8_5E: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $8, $8, $0, $C, $F4
	dc.b $0, $0, $0, $F, $C
DATA67XB17S4UC8_5F: dc.b $5
	dc.b $FB, $D, $0, $0, $EC
	dc.b $EB, $9, $0, $8, $F4
	dc.b $B, $C, $0, $E, $F4
	dc.b $F3, $0, $0, $12, $C
	dc.b $3, $0, $0, $13, $C
DATA67XB17S4UC8_60: dc.b $3
	dc.b $F4, $D, $0, $0, $ED
	dc.b $EC, $8, $0, $8, $F5
	dc.b $4, $9, $0, $B, $F5
DATA67XB17S4UC8_61: dc.b $3
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
	dc.b $4, $0, $0, $10, $9
DATA67XB17S4UC8_62: dc.b $3
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
	dc.b $2, $0, $0, $10, $9
DATA67XB17S4UC8_63: dc.b $3
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
	dc.b $FF, $0, $0, $10, $9
	even